swagger: "2.0"
info:
  description: "caMicroscope"
  version: "2.0.0"
  title: "caMicroscope"
  contact:
    email: "rbirmin@emory.edu"
host: "camicroscope.org"
basePath: "/v2"
tags:
- name: "collection"
  description: "A collection containing slides or collections"
- name: "slide"
  description: "Necessary metadata around a slide"
- name: "marking"
  description: "marking on a slide in OSD logical coordinates"
- name: "marktype"
  description: "metadata for a type of marking"
- name: "template"
  description: "data used to populate a user facing form"
schemes:
- "http"

definitions:
  collection:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      type:
        type: "string"
        description: "What type the collection contains"
        enum:
        - "slide"
        - "collection"
      contents:
        type: "array"
        description: "Ids of the collections or slides contained"
        items:
          type: "integer"

  slide:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      location:
        type: "string"
        description: "The path of the slide"
      mpp:
        type: "number"
        description: "Microns per pixel of the slide"

  feature:
    type: "object"
    properties:
      coordinates:
        type: "array"
        items:
          type: "array"
          items:
            type: "number"

  marking:
    type: "object"
    description: "following geojson standard"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "the id of the associated marking type"
      marktype-id:
        type: "integer"
        format: "int64"
      features:
        type: "array"
        items:
          $ref: "#/definitions/feature"
  marktype:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      slideid:
        type: "integer"
        format: "int64"
      type:
        type: "string"
        enum:
        - "human"
        - "computer"
      name:
        type: "string"
        description: "display name"

  template:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      type:
        type: "string"
      questions:
        type: "array"
        description: "Ids of the collections or slides contained"
        items:
          type: "object"
          properties:
            field:
              type: "string"
            display:
              type: "string"
            type:
              type: "string"
            enum:
              type: "array"
              items: 
                type: "string"

paths:
  /collection:
    post:
      tags:
      - "collection"
      summary: "Create a collection"
      description: ""
      operationId: "newCollection"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Collection to add"
        required: true
        schema:
          $ref: "#/definitions/collection"
      responses:
        405:
          description: "Invalid input"
      security:
      - camic_auth:
        - "write:collection"
        - "read"

  /collection/byName:
    get:
      tags:
      - "pet"
      summary: "Find Collections by name"
      operationId: "collectionByName"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        required: true
        type: "string"
        collectionFormat: "multi"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/collection"
        400:
          description: "Invalid status value"
      security:
      - camic_auth:
        - "read"

securityDefinitions:
  camic_auth:
    type: "oauth2"
    authorizationUrl: "http://camicroscope.org/oauth/dialog"
    flow: "implicit"
    scopes:
      read: "read slides, collections, marks, and templates"
      write:slide: "add slides"
      write:collection: "add collections"
      write:mark: "add mark"
      write:template: "add template"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

externalDocs:
  description: "Find out more"
  url: "http://camicroscope.org"
